import { Donation } from "@/types/donation.type";

export const donations: Donation[] = [
  {
    id: "zaky-1",
    name: "Zaky",
    amount: 55000,
    notes: "Okee",
    date: "21.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "zaky-2",
    name: "Zaky",
    amount: 50000,
    notes: "Oke",
    date: "21.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "radit-1",
    name: "Radit",
    amount: 100000,
    notes: "Bensin operasional",
    date: "19.02.26",
    image: "/images/capture/zaky-1.png",
    category: "out",
  },
  {
    id: "raka-1",
    name: "Raka",
    amount: 36000,
    notes: "Uang rokok",
    date: "20.01.26",
    image: "/images/capture/zaky-1.png",
    category: "out",
  },
  {
    id: "andi-1",
    name: "Andi",
    amount: 250000,
    notes: "Semoga bermanfaat",
    date: "20.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "siti-1",
    name: "Siti",
    amount: 75000,
    notes: "Untuk kebaikan bersama",
    date: "19.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "budi-1",
    name: "Budi",
    amount: 1500000,
    notes: "Tetap semangat!",
    date: "18.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "andik-1",
    name: "Andik",
    amount: 1500000,
    notes: "Korupsi dikit.",
    date: "17.02.25",
    image: "/images/capture/zaky-1.png",
    category: "out",
  },
  {
    id: "rina-1",
    name: "Rina",
    amount: 300000,
    notes: "Semoga lancar",
    date: "17.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "doni-1",
    name: "Doni",
    amount: 125000,
    notes: "Sedikit bantuan",
    date: "16.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "maya-1",
    name: "Maya",
    amount: 2000000,
    notes: "Semoga cepat tercapai",
    date: "15.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "slamet-1",
    name: "Slamet",
    amount: 500000,
    notes: "DP tenda pasak dll",
    date: "14.01.26",
    image: "/images/capture/zaky-1.png",
    category: "out",
  },
  {
    id: "fajar-1",
    name: "Fajar",
    amount: 90000,
    notes: "Ikut berkontribusi",
    date: "14.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "lina-1",
    name: "Lina",
    amount: 450000,
    notes: "Semoga sukses selalu",
    date: "13.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "arif-1",
    name: "Arif",
    amount: 600000,
    notes: "Semangat terus!",
    date: "12.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
  {
    id: "nina-1",
    name: "Nina",
    amount: 110000,
    notes: "Semoga membantu",
    date: "11.02.26",
    image: "/images/capture/zaky-1.png",
    category: "in",
  },
];
