export const donations = [
  {
    id: "zaky-1",
    name: "Zaky",
    amount: 100000000,
    notes: "Oke",
    date: "21 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "zaky-2",
    name: "Zaky",
    amount: 50000,
    notes: "Oke",
    date: "21 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "andi-1",
    name: "Andi",
    amount: 250000,
    notes: "Semoga bermanfaat",
    date: "20 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "siti-1",
    name: "Siti",
    amount: 75000,
    notes: "Untuk kebaikan bersama",
    date: "19 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "budi-1",
    name: "Budi",
    amount: 1500000,
    notes: "Tetap semangat!",
    date: "18 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "rina-1",
    name: "Rina",
    amount: 300000,
    notes: "Semoga lancar",
    date: "17 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "doni-1",
    name: "Doni",
    amount: 125000,
    notes: "Sedikit bantuan",
    date: "16 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "maya-1",
    name: "Maya",
    amount: 2000000,
    notes: "Semoga cepat tercapai",
    date: "15 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "fajar-1",
    name: "Fajar",
    amount: 90000,
    notes: "Ikut berkontribusi",
    date: "14 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "lina-1",
    name: "Lina",
    amount: 450000,
    notes: "Semoga sukses selalu",
    date: "13 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "arif-1",
    name: "Arif",
    amount: 600000,
    notes: "Semangat terus!",
    date: "12 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
  {
    id: "nina-1",
    name: "Nina",
    amount: 110000,
    notes: "Semoga membantu",
    date: "11 Februari 2026",
    image: "/images/capture/zaky-1.png",
  },
];
